version: "3.3"

services:

  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healeniumnet

  healenium:
    image: healenium/hlm-backend:3.2.2
    ports:
      - "7878:7878"
    links:
      - db
    restart: always
    environment:
      - SPRING_CONTAINER_NAME=healenium
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_URL=jdbc:postgresql://db:5432/healenium?currentSchema=healenium
    networks:
      - healeniumnet

  selector-imitator:
    image: healenium/hlm-selector-imitator:1
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healeniumnet

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 32
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - healeniumnet

volumes:
  pgadmin:

networks:
  healeniumnet:
